# Generated by Django 2.2.7 on 2020-06-13 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chemical_composition',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('percentage', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Commodity',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('inventory', models.FloatField()),
                ('price', models.FloatField()),
                ('chemical_composition', models.ManyToManyField(related_name='cheref', to='service.Chemical_composition')),
            ],
        ),
        migrations.AddField(
            model_name='chemical_composition',
            name='element',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='service.Element'),
        ),
    ]
