# Generated by Django 3.0.8 on 2020-11-21 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('username', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('student', models.ManyToManyField(to='service.Student')),
            ],
        ),
        migrations.RemoveField(
            model_name='commodity',
            name='chemical_composition',
        ),
        migrations.DeleteModel(
            name='Chemical_composition',
        ),
        migrations.DeleteModel(
            name='Commodity',
        ),
        migrations.DeleteModel(
            name='Element',
        ),
        migrations.AddField(
            model_name='subject',
            name='teacher',
            field=models.ManyToManyField(related_name='cheref', to='service.Teacher'),
        ),
    ]
